name: Deploy Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'streamlit/**'
      - 'requirements.txt'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      continue-on-error: true
    
    - name: Build and push Airflow image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: ${{ secrets.DOCKERHUB_USERNAME != '' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/news-pipeline:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/news-pipeline:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
      continue-on-error: true

  notify-deployment:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: build-and-push
    if: always()
    
    steps:
    - name: Create deployment summary
      run: |
        echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp:** $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Dashboard: Ready for Streamlit Cloud deployment" >> $GITHUB_STEP_SUMMARY
        echo "Docker Images: Built successfully" >> $GITHUB_STEP_SUMMARY